# Retrieve list of runtime dependencies and their versions
#
# Usage:
#   include(RuntimeDependencies)
#   get_runtime_dependencies(my_target out_runtime_dependency_list)
#   # or:
#   get_shared_library_dependencies(my_target out_runtime_dependency_list)

function(get_shared_library_dependencies target_name out_var)
    set(options ALIASED_TARGET_NAMES USE_ORIGINAL_TARGET_NAME_IF_NO_ALIASED_FOUND)
    set(one_value_args)
    set(multi_value_args)
    cmake_parse_arguments(SLB "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    get_target_property(_linked_libraries ${target_name} LINK_LIBRARIES)
    foreach(_target ${_linked_libraries})
        if(TARGET ${_target})
            get_target_property(_target_type ${_target} TYPE)
            if(_target_type STREQUAL SHARED_LIBRARY OR _target_type STREQUAL MODULE_LIBRARY)
                if(SLB_ALIASED_TARGET_NAMES)
                    get_target_property(_aliased_name ${_target} ALIASED_TARGET)
                    if(_aliased_name)
                        list(APPEND ${out_var} ${_aliased_name})
                    elseif(SLB_USE_ORIGINAL_TARGET_NAME_IF_NO_ALIASED_FOUND)
                        list(APPEND ${out_var} ${_target})
                    endif()
                else()
                    list(APPEND ${out_var} ${_target})
                endif()
                get_shared_library_dependencies(${_target} ${out_var} ${ARGN})
            endif()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES ${out_var})
    set(${out_var} ${${out_var}} PARENT_SCOPE)
endfunction()

function(get_runtime_dependencies target_name out_var)
    get_shared_library_dependencies(${target_name} _dependencies)
    foreach(_target ${_dependencies})
        get_target_property(_target_version ${_target} VERSION)
        string(FIND ${_target} "::" _cut_pos)
        string(SUBSTRING ${_target} 0 ${_cut_pos} _dependency_name)
        list(APPEND ${out_var} "${_dependency_name}:${_target_version}")
    endforeach()
    set(${out_var} ${${out_var}} PARENT_SCOPE)
endfunction()
