set(INCLUDES
    include/arrayview/ArrayView.h
    include/arrayview/StringView.h
    include/arrayview/version/Version.h
    include/dna/BinaryStreamReader.h
    include/dna/BinaryStreamWriter.h
    include/dna/Configuration.h
    include/dna/Defs.h
    include/dna/JSONStreamReader.h
    include/dna/JSONStreamWriter.h
    include/dna/Reader.h
    include/dna/StreamReader.h
    include/dna/StreamWriter.h
    include/dna/Writer.h
    include/dna/layers/BehaviorReader.h
    include/dna/layers/BehaviorWriter.h
    include/dna/layers/DefinitionReader.h
    include/dna/layers/DefinitionWriter.h
    include/dna/layers/Descriptor.h
    include/dna/layers/DescriptorReader.h
    include/dna/layers/DescriptorWriter.h
    include/dna/layers/Geometry.h
    include/dna/layers/GeometryReader.h
    include/dna/layers/GeometryWriter.h
    include/dna/layers/HeaderReader.h
    include/dna/layers/HeaderWriter.h
    include/dna/layers/JointBehaviorMetadata.h
    include/dna/layers/JointBehaviorMetadataReader.h
    include/dna/layers/JointBehaviorMetadataWriter.h
    include/dna/layers/MachineLearnedBehavior.h
    include/dna/layers/MachineLearnedBehaviorExt.h
    include/dna/layers/MachineLearnedBehaviorExtReader.h
    include/dna/layers/MachineLearnedBehaviorExtWriter.h
    include/dna/layers/MachineLearnedBehaviorReader.h
    include/dna/layers/MachineLearnedBehaviorWriter.h
    include/dna/layers/RBFBehavior.h
    include/dna/layers/RBFBehaviorReader.h
    include/dna/layers/RBFBehaviorWriter.h
    include/dna/layers/Twist.h
    include/dna/layers/TwistSwingBehaviorReader.h
    include/dna/layers/TwistSwingBehaviorWriter.h
    include/dna/types/Aliases.h
    include/dna/types/Vector3.h
    include/dna/version/Version.h
    include/dna/version/VersionInfo.h
    include/pma/Defs.h
    include/pma/MemoryResource.h
    include/pma/PolyAllocator.h
    include/pma/ScopedPtr.h
    include/pma/TypeDefs.h
    include/pma/resources/AlignedMemoryResource.h
    include/pma/resources/ArenaMemoryResource.h
    include/pma/resources/DefaultMemoryResource.h
    include/pma/utils/ManagedInstance.h
    include/pma/version/Version.h
    include/riglogic/Defs.h
    include/riglogic/RigLogic.h
    include/riglogic/riglogic/Configuration.h
    include/riglogic/riglogic/RigInstance.h
    include/riglogic/riglogic/RigLogic.h
    include/riglogic/riglogic/Stats.h
    include/riglogic/types/Aliases.h
    include/riglogic/version/Version.h
    include/riglogic/version/VersionInfo.h
    include/status/Defs.h
    include/status/Provider.h
    include/status/Status.h
    include/status/StatusCode.h
    include/status/version/Version.h
    include/tdm/Ang.h
    include/tdm/Computations.h
    include/tdm/CoordSys.h
    include/tdm/Mat.h
    include/tdm/Quat.h
    include/tdm/TDM.h
    include/tdm/Transforms.h
    include/tdm/Types.h
    include/tdm/Vec.h
    include/tdm/version/Version.h
    include/trio/Concepts.h
    include/trio/Defs.h
    include/trio/Stream.h
    include/trio/streams/FileStream.h
    include/trio/streams/MemoryMappedFileStream.h
    include/trio/streams/MemoryStream.h
    include/trio/types/Aliases.h
    include/trio/types/Parameters.h
    include/trio/utils/StreamScope.h
    include/trio/version/Version.h)
set(SOURCES
    src/dna/BaseImpl.h
    src/dna/DNA.h
    src/dna/DataLayerBitmask.h
    src/dna/DenormalizedData.h
    src/dna/Helpers.h
    src/dna/LODConstraint.cpp
    src/dna/LODConstraint.h
    src/dna/LODMapping.cpp
    src/dna/LODMapping.h
    src/dna/Reader.cpp
    src/dna/ReaderImpl.h
    src/dna/SurjectiveMapping.h
    src/dna/TypeDefs.h
    src/dna/Writer.cpp
    src/dna/WriterImpl.h
    src/dna/filters/AnimatedMapFilter.cpp
    src/dna/filters/AnimatedMapFilter.h
    src/dna/filters/BlendShapeFilter.cpp
    src/dna/filters/BlendShapeFilter.h
    src/dna/filters/JointFilter.cpp
    src/dna/filters/JointFilter.h
    src/dna/filters/MeshFilter.cpp
    src/dna/filters/MeshFilter.h
    src/dna/filters/Remap.h
    src/dna/stream/BinaryStreamReaderImpl.cpp
    src/dna/stream/BinaryStreamReaderImpl.h
    src/dna/stream/BinaryStreamWriterImpl.cpp
    src/dna/stream/BinaryStreamWriterImpl.h
    src/dna/stream/FilteredBinaryInputArchive.cpp
    src/dna/stream/FilteredBinaryInputArchive.h
    src/dna/stream/JSONStreamReaderImpl.cpp
    src/dna/stream/JSONStreamReaderImpl.h
    src/dna/stream/JSONStreamWriterImpl.cpp
    src/dna/stream/JSONStreamWriterImpl.h
    src/dna/stream/StreamReader.cpp
    src/dna/stream/StreamReaderStatus.h
    src/dna/stream/StreamWriter.cpp
    src/dna/types/CoordinateSystemConverter.cpp
    src/dna/types/CoordinateSystemConverter.h
    src/dna/types/Limits.h
    src/dna/utils/Extd.h
    src/dna/utils/Macros.h
    src/dna/utils/ScopedEnumEx.h
    src/dna/version/DNAVersionInfo.cpp
    src/pma/MemoryResource.cpp
    src/pma/resources/AlignedMemoryResource.cpp
    src/pma/resources/ArenaMemoryResource.cpp
    src/pma/resources/DefaultMemoryResource.cpp
    src/riglogic/TypeDefs.h
    src/riglogic/animatedmaps/AnimatedMaps.cpp
    src/riglogic/animatedmaps/AnimatedMaps.h
    src/riglogic/animatedmaps/AnimatedMapsFactory.cpp
    src/riglogic/animatedmaps/AnimatedMapsFactory.h
    src/riglogic/animatedmaps/AnimatedMapsImpl.cpp
    src/riglogic/animatedmaps/AnimatedMapsImpl.h
    src/riglogic/animatedmaps/AnimatedMapsImplOutputInstance.cpp
    src/riglogic/animatedmaps/AnimatedMapsImplOutputInstance.h
    src/riglogic/animatedmaps/AnimatedMapsNull.cpp
    src/riglogic/animatedmaps/AnimatedMapsNull.h
    src/riglogic/animatedmaps/AnimatedMapsNullOutputInstance.cpp
    src/riglogic/animatedmaps/AnimatedMapsNullOutputInstance.h
    src/riglogic/animatedmaps/AnimatedMapsOutputInstance.cpp
    src/riglogic/animatedmaps/AnimatedMapsOutputInstance.h
    src/riglogic/blendshapes/BlendShapes.cpp
    src/riglogic/blendshapes/BlendShapes.h
    src/riglogic/blendshapes/BlendShapesFactory.cpp
    src/riglogic/blendshapes/BlendShapesFactory.h
    src/riglogic/blendshapes/BlendShapesImpl.cpp
    src/riglogic/blendshapes/BlendShapesImpl.h
    src/riglogic/blendshapes/BlendShapesImplOutputInstance.cpp
    src/riglogic/blendshapes/BlendShapesImplOutputInstance.h
    src/riglogic/blendshapes/BlendShapesNull.cpp
    src/riglogic/blendshapes/BlendShapesNull.h
    src/riglogic/blendshapes/BlendShapesNullOutputInstance.cpp
    src/riglogic/blendshapes/BlendShapesNullOutputInstance.h
    src/riglogic/blendshapes/BlendShapesOutputInstance.cpp
    src/riglogic/blendshapes/BlendShapesOutputInstance.h
    src/riglogic/conditionaltable/ConditionalTable.cpp
    src/riglogic/conditionaltable/ConditionalTable.h
    src/riglogic/controls/Controls.cpp
    src/riglogic/controls/Controls.h
    src/riglogic/controls/ControlsFactory.cpp
    src/riglogic/controls/ControlsFactory.h
    src/riglogic/controls/ControlsInputInstance.cpp
    src/riglogic/controls/ControlsInputInstance.h
    src/riglogic/controls/instances/StandardControlsInputInstance.cpp
    src/riglogic/controls/instances/StandardControlsInputInstance.h
    src/riglogic/joints/JointBehaviorFilter.cpp
    src/riglogic/joints/JointBehaviorFilter.h
    src/riglogic/joints/Joints.cpp
    src/riglogic/joints/Joints.h
    src/riglogic/joints/JointsBuilder.cpp
    src/riglogic/joints/JointsBuilder.h
    src/riglogic/joints/JointsEvaluator.cpp
    src/riglogic/joints/JointsEvaluator.h
    src/riglogic/joints/JointsFactory.cpp
    src/riglogic/joints/JointsFactory.h
    src/riglogic/joints/JointsNullEvaluator.cpp
    src/riglogic/joints/JointsNullEvaluator.h
    src/riglogic/joints/JointsNullOutputInstance.cpp
    src/riglogic/joints/JointsNullOutputInstance.h
    src/riglogic/joints/JointsOutputInstance.cpp
    src/riglogic/joints/JointsOutputInstance.h
    src/riglogic/joints/cpu/CPUJointsBuilder.cpp
    src/riglogic/joints/cpu/CPUJointsBuilder.h
    src/riglogic/joints/cpu/CPUJointsEvaluator.cpp
    src/riglogic/joints/cpu/CPUJointsEvaluator.h
    src/riglogic/joints/cpu/CPUJointsOutputInstance.cpp
    src/riglogic/joints/cpu/CPUJointsOutputInstance.h
    src/riglogic/joints/cpu/bpcm/BPCMCalculationStrategy.cpp
    src/riglogic/joints/cpu/bpcm/BPCMCalculationStrategy.h
    src/riglogic/joints/cpu/bpcm/BPCMJointsBuilder.cpp
    src/riglogic/joints/cpu/bpcm/BPCMJointsBuilder.h
    src/riglogic/joints/cpu/bpcm/BPCMJointsBuilderFactory.cpp
    src/riglogic/joints/cpu/bpcm/BPCMJointsBuilderFactory.h
    src/riglogic/joints/cpu/bpcm/BPCMJointsEvaluator.cpp
    src/riglogic/joints/cpu/bpcm/BPCMJointsEvaluator.h
    src/riglogic/joints/cpu/bpcm/JointGroup.h
    src/riglogic/joints/cpu/bpcm/RotationAdapters.h
    src/riglogic/joints/cpu/bpcm/Storage.h
    src/riglogic/joints/cpu/ml/CoordinateSystemTransformer.h
    src/riglogic/joints/cpu/ml/MLJointsBuilder.cpp
    src/riglogic/joints/cpu/ml/MLJointsBuilder.h
    src/riglogic/joints/cpu/ml/MLJointsBuilderFactory.cpp
    src/riglogic/joints/cpu/ml/MLJointsBuilderFactory.h
    src/riglogic/joints/cpu/ml/MLJointsEvaluator.h
    src/riglogic/joints/cpu/ml/RotationAdapters.h
    src/riglogic/joints/cpu/quaternions/JointGroup.h
    src/riglogic/joints/cpu/quaternions/QuaternionCalculationStrategy.cpp
    src/riglogic/joints/cpu/quaternions/QuaternionCalculationStrategy.h
    src/riglogic/joints/cpu/quaternions/QuaternionJointsBuilder.cpp
    src/riglogic/joints/cpu/quaternions/QuaternionJointsBuilder.h
    src/riglogic/joints/cpu/quaternions/QuaternionJointsBuilderFactory.cpp
    src/riglogic/joints/cpu/quaternions/QuaternionJointsBuilderFactory.h
    src/riglogic/joints/cpu/quaternions/QuaternionJointsEvaluator.cpp
    src/riglogic/joints/cpu/quaternions/QuaternionJointsEvaluator.h
    src/riglogic/joints/cpu/quaternions/RotationAdapters.h
    src/riglogic/joints/cpu/twistswing/TwistSwingJointsBuilder.h
    src/riglogic/joints/cpu/twistswing/TwistSwingJointsBuilderFactory.cpp
    src/riglogic/joints/cpu/twistswing/TwistSwingJointsBuilderFactory.h
    src/riglogic/joints/cpu/twistswing/TwistSwingJointsEvaluator.h
    src/riglogic/joints/cpu/twistswing/TwistSwingSetup.h
    src/riglogic/joints/cpu/utils/JointGroupOptimizer.cpp
    src/riglogic/joints/cpu/utils/JointGroupOptimizer.h
    src/riglogic/joints/cpu/utils/LODRegion.h
    src/riglogic/ml/MachineLearnedBehavior.cpp
    src/riglogic/ml/MachineLearnedBehavior.h
    src/riglogic/ml/MachineLearnedBehaviorEvaluator.cpp
    src/riglogic/ml/MachineLearnedBehaviorEvaluator.h
    src/riglogic/ml/MachineLearnedBehaviorFactory.cpp
    src/riglogic/ml/MachineLearnedBehaviorFactory.h
    src/riglogic/ml/MachineLearnedBehaviorNullEvaluator.cpp
    src/riglogic/ml/MachineLearnedBehaviorNullEvaluator.h
    src/riglogic/ml/MachineLearnedBehaviorNullOutputInstance.cpp
    src/riglogic/ml/MachineLearnedBehaviorNullOutputInstance.h
    src/riglogic/ml/MachineLearnedBehaviorOutputInstance.cpp
    src/riglogic/ml/MachineLearnedBehaviorOutputInstance.h
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorEvaluator.cpp
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorEvaluator.h
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorFactory.cpp
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorFactory.h
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorOutputInstance.cpp
    src/riglogic/ml/cpu/CPUMachineLearnedBehaviorOutputInstance.h
    src/riglogic/ml/cpu/NeuralNet.h
    src/riglogic/ml/cpu/Operation.cpp
    src/riglogic/ml/cpu/Operation.h
    src/riglogic/ml/cpu/layers/LayerEvaluator.h
    src/riglogic/ml/cpu/layers/LeakyReLULayerEvaluator.h
    src/riglogic/ml/cpu/layers/LinearLayerEvaluator.h
    src/riglogic/ml/cpu/layers/ReLULayerEvaluator.h
    src/riglogic/ml/cpu/layers/SigmoidLayerEvaluator.h
    src/riglogic/ml/cpu/layers/TanHLayerEvaluator.h
    src/riglogic/ml/cpu/layers/Utils.h
    src/riglogic/psdnet/PSDNet.cpp
    src/riglogic/psdnet/PSDNet.h
    src/riglogic/psdnet/PSDNetFactory.cpp
    src/riglogic/psdnet/PSDNetFactory.h
    src/riglogic/psdnet/PSDNetImpl.cpp
    src/riglogic/psdnet/PSDNetImpl.h
    src/riglogic/psdnet/PSDNetImplOutputInstance.cpp
    src/riglogic/psdnet/PSDNetImplOutputInstance.h
    src/riglogic/psdnet/PSDNetNull.cpp
    src/riglogic/psdnet/PSDNetNull.h
    src/riglogic/psdnet/PSDNetNullOutputInstance.cpp
    src/riglogic/psdnet/PSDNetNullOutputInstance.h
    src/riglogic/psdnet/PSDNetOutputInstance.cpp
    src/riglogic/psdnet/PSDNetOutputInstance.h
    src/riglogic/rbf/RBFBehavior.cpp
    src/riglogic/rbf/RBFBehavior.h
    src/riglogic/rbf/RBFBehaviorEvaluator.cpp
    src/riglogic/rbf/RBFBehaviorEvaluator.h
    src/riglogic/rbf/RBFBehaviorFactory.cpp
    src/riglogic/rbf/RBFBehaviorFactory.h
    src/riglogic/rbf/RBFBehaviorNullEvaluator.cpp
    src/riglogic/rbf/RBFBehaviorNullEvaluator.h
    src/riglogic/rbf/RBFBehaviorNullOutputInstance.cpp
    src/riglogic/rbf/RBFBehaviorNullOutputInstance.h
    src/riglogic/rbf/RBFBehaviorOutputInstance.cpp
    src/riglogic/rbf/RBFBehaviorOutputInstance.h
    src/riglogic/rbf/cpu/AdditiveRBFSolver.cpp
    src/riglogic/rbf/cpu/AdditiveRBFSolver.h
    src/riglogic/rbf/cpu/CPURBFBehaviorEvaluator.h
    src/riglogic/rbf/cpu/CPURBFBehaviorFactory.h
    src/riglogic/rbf/cpu/CPURBFBehaviorOutputInstance.cpp
    src/riglogic/rbf/cpu/CPURBFBehaviorOutputInstance.h
    src/riglogic/rbf/cpu/InterpolativeRBFSolver.cpp
    src/riglogic/rbf/cpu/InterpolativeRBFSolver.h
    src/riglogic/rbf/cpu/RBFSolver.cpp
    src/riglogic/rbf/cpu/RBFSolver.h
    src/riglogic/riglogic/ConfigurationSerializer.h
    src/riglogic/riglogic/RigInstanceImpl.cpp
    src/riglogic/riglogic/RigInstanceImpl.h
    src/riglogic/riglogic/RigLogicImpl.cpp
    src/riglogic/riglogic/RigLogicImpl.h
    src/riglogic/riglogic/RigMetadata.h
    src/riglogic/system/simd/Detect.h
    src/riglogic/system/simd/SIMD.h
    src/riglogic/system/simd/Utils.h
    src/riglogic/types/Extent.h
    src/riglogic/types/LODSpec.h
    src/riglogic/types/PaddedBlockView.h
    src/riglogic/types/bpcm/FloatArray.h
    src/riglogic/types/bpcm/Optimizer.h
    src/riglogic/utils/Extd.h
    src/riglogic/utils/Macros.h
    src/riglogic/version/RLVersionInfo.cpp
    src/status/PredefinedCodes.h
    src/status/Provider.cpp
    src/status/Registry.cpp
    src/status/Registry.h
    src/status/Status.cpp
    src/status/Storage.cpp
    src/status/Storage.h
    src/terse/Archive.h
    src/terse/archives/Common.h
    src/terse/archives/Traits.h
    src/terse/archives/binary/InputArchive.h
    src/terse/archives/binary/OutputArchive.h
    src/terse/archives/json/InputArchive.h
    src/terse/archives/json/OutputArchive.h
    src/terse/types/Anchor.h
    src/terse/types/ArchiveOffset.h
    src/terse/types/ArchiveSize.h
    src/terse/types/Blob.h
    src/terse/types/CharInputStreamBuf.h
    src/terse/types/CharOutputStreamBuf.h
    src/terse/types/DynArray.h
    src/terse/types/Transparent.h
    src/terse/types/Versioned.h
    src/terse/utils/Base64.h
    src/terse/utils/ByteSwap.h
    src/terse/utils/Endianness.h
    src/terse/utils/VirtualSerializerProxy.h
    src/terse/version/Version.h
    src/trimd/AVX.h
    src/trimd/Fallback.h
    src/trimd/Macros.h
    src/trimd/NEON.h
    src/trimd/Platform.h
    src/trimd/PlatformWindows.h
    src/trimd/Polyfill.h
    src/trimd/SSE.h
    src/trimd/Scalar.h
    src/trimd/TRiMD.h
    src/trimd/Utils.h
    src/trimd/version/Version.h
    src/trio/Concepts.cpp
    src/trio/Stream.cpp
    src/trio/streams/FileStreamImpl.cpp
    src/trio/streams/FileStreamImpl.h
    src/trio/streams/MemoryMappedFileStream.cpp
    src/trio/streams/MemoryMappedFileStreamFallback.cpp
    src/trio/streams/MemoryMappedFileStreamFallback.h
    src/trio/streams/MemoryMappedFileStreamUnix.cpp
    src/trio/streams/MemoryMappedFileStreamUnix.h
    src/trio/streams/MemoryMappedFileStreamWindows.cpp
    src/trio/streams/MemoryMappedFileStreamWindows.h
    src/trio/streams/MemoryStreamImpl.cpp
    src/trio/streams/MemoryStreamImpl.h
    src/trio/streams/StreamStatus.cpp
    src/trio/streams/StreamStatus.h
    src/trio/utils/NativeString.h
    src/trio/utils/PlatformWindows.h
    src/trio/utils/ScopedEnumEx.h)
set(TESTS
    tests/TestRunner.cpp
    tests/arrayviewtests/Defs.h
    tests/arrayviewtests/TestArrayView.cpp
    tests/arrayviewtests/TestArrayView.h
    tests/arrayviewtests/TestStringView.cpp
    tests/arrayviewtests/Utils.h
    tests/dnatests/Defs.h
    tests/dnatests/FakeDNAReader.cpp
    tests/dnatests/FakeDNAReader.h
    tests/dnatests/FixturesJSON.cpp
    tests/dnatests/FixturesJSON.h
    tests/dnatests/Fixturesv21.cpp
    tests/dnatests/Fixturesv21.h
    tests/dnatests/Fixturesv22.cpp
    tests/dnatests/Fixturesv22.h
    tests/dnatests/Fixturesv23.cpp
    tests/dnatests/Fixturesv23.h
    tests/dnatests/Fixturesv24.cpp
    tests/dnatests/Fixturesv24.h
    tests/dnatests/Fixturesv25.cpp
    tests/dnatests/Fixturesv25.h
    tests/dnatests/Fixturesv26.cpp
    tests/dnatests/Fixturesv26.h
    tests/dnatests/Fixturesv27.cpp
    tests/dnatests/Fixturesv27.h
    tests/dnatests/Fixturesv28.cpp
    tests/dnatests/Fixturesv28.h
    tests/dnatests/TestBinaryStreamWriter.cpp
    tests/dnatests/TestBinaryStreamWriter.h
    tests/dnatests/TestFilteredBinaryInputArchive.cpp
    tests/dnatests/TestLODConstraint.cpp
    tests/dnatests/TestLODMapping.cpp
    tests/dnatests/TestMalformedInput.cpp
    tests/dnatests/TestStreamReadWriteIntegration.cpp
    tests/dnatests/TestStreamReadWriteIntegration.h
    tests/pmatests/Defs.h
    tests/pmatests/TestPolyAllocIntegration.cpp
    tests/pmatests/TestScopedPtr.cpp
    tests/pmatests/resources/TestAlignedMemoryResource.cpp
    tests/pmatests/resources/TestArenaMemoryResource.cpp
    tests/pmatests/utils/TestManagedInstance.cpp
    tests/rltests/Defs.h
    tests/rltests/StorageValueType.h
    tests/rltests/animatedmaps/AnimatedMapFixtures.cpp
    tests/rltests/animatedmaps/AnimatedMapFixtures.h
    tests/rltests/animatedmaps/TestAnimatedMaps.cpp
    tests/rltests/blendshapes/BlendShapeFixtures.cpp
    tests/rltests/blendshapes/BlendShapeFixtures.h
    tests/rltests/blendshapes/TestBlendShapes.cpp
    tests/rltests/conditionaltable/ConditionalTableFixtures.cpp
    tests/rltests/conditionaltable/ConditionalTableFixtures.h
    tests/rltests/conditionaltable/TestConditionalTable.cpp
    tests/rltests/controls/ControlFixtures.cpp
    tests/rltests/controls/ControlFixtures.h
    tests/rltests/controls/TestControls.cpp
    tests/rltests/dna/DNAFixtures.cpp
    tests/rltests/dna/DNAFixtures.h
    tests/rltests/dna/FakeReader.cpp
    tests/rltests/dna/FakeReader.h
    tests/rltests/joints/Helpers.h
    tests/rltests/joints/TestJointsFactory.cpp
    tests/rltests/joints/bpcm/Assertions.h
    tests/rltests/joints/bpcm/BPCMFixturesBlock4.cpp
    tests/rltests/joints/bpcm/BPCMFixturesBlock4.h
    tests/rltests/joints/bpcm/BPCMFixturesBlock8.cpp
    tests/rltests/joints/bpcm/BPCMFixturesBlock8.h
    tests/rltests/joints/bpcm/Helpers.h
    tests/rltests/joints/bpcm/TestBlock4CalculationStrategy.cpp
    tests/rltests/joints/bpcm/TestBlock4StorageBuilder.cpp
    tests/rltests/joints/bpcm/TestBlock8CalculationStrategy.cpp
    tests/rltests/joints/bpcm/TestBlock8StorageBuilder.cpp
    tests/rltests/joints/quaternions/QuaternionFixtures.cpp
    tests/rltests/joints/quaternions/QuaternionFixtures.h
    tests/rltests/joints/quaternions/TestQuaternionEvaluator.cpp
    tests/rltests/joints/quaternions/TestQuaternionStorageBuilder.cpp
    tests/rltests/joints/twistswing/TestTwistSwingEvaluator.cpp
    tests/rltests/joints/twistswing/TestTwistSwingStorageBuilder.cpp
    tests/rltests/joints/twistswing/TwistSwingFixtures.cpp
    tests/rltests/joints/twistswing/TwistSwingFixtures.h
    tests/rltests/joints/utils/TestLODRegion.cpp
    tests/rltests/ml/cpu/FixturesBlock4.cpp
    tests/rltests/ml/cpu/FixturesBlock4.h
    tests/rltests/ml/cpu/FixturesMLBChained.cpp
    tests/rltests/ml/cpu/FixturesMLBChained.h
    tests/rltests/ml/cpu/TestInference.cpp
    tests/rltests/ml/cpu/TestMLBChained.cpp
    tests/rltests/ml/cpu/TestStorageBuilder.cpp
    tests/rltests/psdnet/TestPSDNet.cpp
    tests/rltests/rbf/cpu/RBFFixtures.cpp
    tests/rltests/rbf/cpu/RBFFixtures.h
    tests/rltests/rbf/cpu/TestRBFEvaluator.cpp
    tests/rltests/rbf/cpu/TestRBFSolver.cpp
    tests/rltests/rbf/cpu/TestRBFStorageBuilder.cpp
    tests/rltests/riglogic/TestRigLogic.cpp
    tests/sctests/Defs.h
    tests/sctests/TestStatusProviderIntegration.cpp
    tests/tdmtests/Defs.h
    tests/tdmtests/Helpers.h
    tests/tdmtests/TestAng.cpp
    tests/tdmtests/TestComputations.cpp
    tests/tdmtests/TestCoordSys.cpp
    tests/tdmtests/TestMat.cpp
    tests/tdmtests/TestQuat.cpp
    tests/tdmtests/TestTransforms.cpp
    tests/tdmtests/TestVec.cpp
    tests/tersetests/Defs.h
    tests/tersetests/FakeStream.h
    tests/tersetests/archives/binary/Common.h
    tests/tersetests/archives/binary/TestBinaryInputArchive.cpp
    tests/tersetests/archives/binary/TestBinaryOutputArchive.cpp
    tests/tersetests/archives/json/Common.h
    tests/tersetests/archives/json/TestJSONInputArchive.cpp
    tests/tersetests/archives/json/TestJSONOutputArchive.cpp
    tests/tersetests/types/TestArchiveOffset.cpp
    tests/tersetests/types/TestArchiveSize.cpp
    tests/tersetests/types/TestCharInputStreamBuf.cpp
    tests/tersetests/types/TestCharOutputStreamBuf.cpp
    tests/tersetests/types/TestDynArray.cpp
    tests/tersetests/utils/TestBase64.cpp
    tests/trimdtests/Defs.h
    tests/trimdtests/TestPlatform.cpp
    tests/trimdtests/TestT128.cpp
    tests/trimdtests/TestT256.cpp
    tests/triotests/Defs.h
    tests/triotests/TestStreams.cpp
    tests/triotests/TestStreams.h
    tests/triotests/TestStreamsIntegration.cpp)
